/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XCoinSale } from "./XCoinSale";
export type { XCoinSaleV2 } from "./XCoinSaleV2";
export type { XCoinToken } from "./XCoinToken";
export type { XCoinVault } from "./XCoinVault";
